---
- name: install bind and bind-utils
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
     - bind
     - bind-utils
  tags: named

- name: Configure named config file
  template: src=named.conf.j2 dest=/etc/named.conf
  tags: named
  notify: restart named

- name: l4rs.net zone files
  template: src=l4rs.net.db.j2 dest=/var/named/l4rs.net.db
  tags: named
  notify: restart named

- name: 192.168 zone files
  template: src=192.168.db.j2 dest=/var/named/192.168.db
  tags: named
  notify: restart named
